---

bind_listen_ipv4:
  - any
bind_allow_query:
  - any

bind_zone_networks:
  - '192.0.2'
  - '172.16'
bind_zone_name: 'avalon.lan'
bind_zone_master_server_ip: 192.0.2.10
bind_zone_name_servers:
  - pu001
  - pu002
bind_zone_hosts:
- name: pu001
  ip: 192.0.2.10
  aliases: 
    - ns1
- name: pu002
  ip: 192.0.2.11
  aliases: 
    - ns2
