version: '2'

services:
    web:
        build: web

    proxy:
        build: proxy
        ports:
          - "8000:80"
          # Docker zoekt automatisch andere server op via eigen DNS-server 127.0.0.11